### ISSUE TITLE
Projet

### ISSUE THREAD

**Issue by espitall** [Kev-J/ausbee#20]
Le commit 1683d681c96530cfba16a675f89ba60c9ae20c18 a cassé la gestion de projet.

Principalement il manque le répertoire Project. Ensuite, je ne suis pas convaincu que Makefile soit le meilleur outil pour créer un projet vide, un script aurait surement été plus pratique afin de pouvoir l'utiliser ailleurs que dans le répertoire principal sans difficultés.

**Comment by astralien3000** [comment]
Pour info, dans les Makefiles d'Aversive++, on met une variable AVERSIVE_ROOT (pour vous, ça serait AUSBEE_ROOT), qu'on demande de modifier au début de son projet. Et à partir de cette variable, on fait tout les appels utiles (scripts, binaires, etc...). Ça permet de mettre son dossier de projet n'importe où sans trop de difficultés.
On pense même mettre la variable en variable d'environnement. Comme ça l'utilisateur n'a qu'à la mettre dans son bashrc et tout les projets compilerons sans aucune modification !

**Comment by espitall** [comment]
Yep, effectivement il y a AUSBEE_DIR ;) La je pense le soucis c'est plus un commit partiel de @Kev-J !

**Comment by Kev-J** [comment]
Oups, gitignore a filtré mes modifs... Le contenu de Projects ne devait pas
être pushé car il ne contenait a la base que des .c .h utilisateur.

je corrige ça ce soir.

2015-10-20 12:30 GMT+02:00 espitall <notifications@github.com>:

**Comment by Kev-J** [comment]
Corrigé ;)
