### ISSUE TITLE
Proposition de fusion avec Aversive++

### ISSUE THREAD

**Issue by astralien3000** [Kev-J/ausbee#4]
Salut l'équipe AUSBEE !

Je viens mettre sur la table une proposition de fusion entre Aversive++ et la libAUSBEE, que j'ai très brièvement évoqué avec Vincent à la fin de la coupe.
Je sais qu'il y a pas mal de points différents entre les deux libs : 
- C vs C++
- menuconfig vs quedalle
- StdPeriph vs STM32Cube (enfin pas vraiment, c'est pas officiel)
- etc ?

Perso je travaille depuis plusieurs mois (de façon sporadique, il faut l'avouer) pour rendre Aversive++ facilement extensible grâce à un système de modules et de distributions, ce qui peut faciliter la fusion. Je trouverai ça cool de pouvoir réunir nos codes.

Donc voila j'aimerai avoir vos avis sur la question. Et si vous voulez parler des détails ici, ou par mail ou encore ailleurs.

**Comment by espitall** [comment]
Hello,

C'est marrant, je viens juste de m'impliquer dans AUSBEE histoire d'avoir un code de base compatible le plus possible avec Eirbot, histoire qu'un coup de pouce à la coupe soit plus facile.

Je serais a 100% pour un aversive++ mergé avec AUSBEE, ca serait l'été de la réunification !

Après je suis extérieur a AUSBEE donc mon avis ne compte pas :)

Damien

**Comment by Kev-J** [comment]
Salut Loic,

Merci pour ta proposition intéressante.
Je vais répondre à l'envers de tes 3 points:
- Etant donné que StdPeriph est deprecated, Stm32Cube sera intégré
prochainement dans Ausbee.
- Maintenant qu'on à investi pas mal de temps pour mettre en place un
menuconfig, je pense le garder !
- Le point le plus bloquant est le C++. Nous avons testé de compiler un
projet en C++ sur du STM32. Celà se complique clairement une fois qu'on
souhaite utiliser le polymorphisme : la taille du programme explose et
c'est pas acceptable pour les petits stm32. Plutôt que d'utiliser une lib
en C pour les petits STM32 et une lib en C++ pour les plus gros nous avons
décidé de rester sur du C qui, à mon sens, reste plus adapté pour nos
petites cibles embarquées.

Bien sûr la discussion est ouverte, je ne fais que citer nos résultats de
l'année passée.

Kev,

**Comment by astralien3000** [comment]
#### menuconfig

Alors, déjà en ce qui concerne le menuconfig, il n'y aura sûrement aucune raison de le supprimer. Mais il se peut que la libAUSBEE ne soit plus configurée par ça.

En effet, mon premier objectif est de fusionner la libAUSBEE avec Aversive++, et pas tout AUSBEE (j'ai peut être pas posté sur le bon dépôt d'ailleurs, mais bon, maintenant qu'on est lancé !). Et aux dernière nouvelles, le menuconfig ne gère pas grand chose de ce côté là (à part l'inclusion des modules dans le projet), à moins que ça ait changé ?

Pour FreeRTOS, je t'avouerai franchement que ça m'intéresse pas de l'inclure dans la fusion. Après on peut s'arranger si ça te semble important.

Ce que je reproche au menuconfig, c'est qu'il demande d'inclure ou retirer les modules de code en changeant la configuration, alors qu'un système de bibliothèque statique permet de ne charger que les modules utilisés par le code utilisateur, et cela automatiquement.

#### C vs C++

Alors, je viens de faire un étude pour comparer un code C++ (avec Aversive++) avec un code C (avec Aversive) sur architecture AVR : 
https://github.com/astralien3000/aversive--/blob/modules/doc/comparison/comp_size.txt

Voici les données à partir desquelles j'ai travaillé : 
https://github.com/astralien3000/aversive--/blob/modules/doc/comparison/aversive_size.log
https://github.com/astralien3000/aversive--/blob/modules/doc/comparison/aversive%2B%2B_size.log

Très intéressante cette étude, je sais sur quoi je doit travailler maintenant !

En ce qui concerne la RAM, je n'ai pas d'étude précise sur le sujet (dû au fait que la plupart des variables sont allouées sur la pile dans le code aversive étudié), mais je pense qu'à cause du polymorphisme, on doit attendre les 10-20% de mémoire en plus.

Cependant on a quand même fait tourner en 2014 à peu près les mêmes fonctionnalités, voir plus, que les 1A qui utilisaient Aversive (pathfinding, représentation vectorielle du terrain, détection, stratégie complexe, etc...), et on arrivait à des utilisation de RAM équivalentes.

Pour un résumé général, bien sûre qu'il y a un surcoût du C++, surtout quand on utilises le polymorphisme ou d'autres fonctionnalités. Mais 20% de taille en mémoire en plus, j'appelle pas ça une explosion (à part pour le scheduler, mais là j'ai un peu foiré...).

Surtout que je n'ai pas fait le choix du C++ pour le polymorphisme, mais pour les templates. Après, j'avoue que je suis un faible et que j'ai quand même un peu utilisé le polymorphisme, alors qu'il y a des techniques qui permettent de s'en passer.

#### Les questions importantes

En gros je voudrai pouvoir faire en sorte que les deux projets contribuent à une même interface, qui soit compatible pour STM32 et AVR, afin de faciliter la transition pour Eirbot, et aussi permettre de mixer les architecture facilement.

Personnellement, quelques fonction de style C ne me dérangent pas, vu que le C++ le gère.

On est pas obligé de tout partager (le système de compilation par exemple), mais au moins une partie ça serait cool.

Il y a donc 2 question importantes : 
Est-ce que le fait d'avoir le langage C++ comme interface est rebutant au point de laisser tomber la fusion quoi qu'il arrive ?
Qui est motivé pour contribuer à la fusion si elle a lieu ?

**Comment by Kev-J** [comment]
Effectivement j'ai lu trop vite.

Perso je pense que c'est une mauvaise idée de brider l'utilisateur de la
libausbee à coder uniquement en C++. Surtout après nos tests avec g++ sur
arm. Ca forcerait l'utilisation de libAUSBEE uniquement sur les plus gros
STM32.

Je pense que pour ton cas d'utilisation, le plus adapté serait de te servir
de libausbee pour ce que tu as besoin. Rien ne t'empêche de commit sur
libausbee également. Tu peux même l'intégrer automatiquement dans ton
projet en wget une release https://github.com/Kev-J/libausbee/releases

La force de la chose permettrais d'avoir une seule et même lib d'asserv' et
de driver utilisable pour tous.

Rien ne t'empêche aussi de wrapper les composantes de la lib dans des
classes C++.

Pour tes 2 questions finales (dans l'ordre):
- Oui, celà impliquerait de priver les petits stm32 de libausbee.
- Nous sommes tous prêt à t'aider à l'intégrer mais tout réecrire en C++ me
semble très peu judicieux.

Kev,

**Comment by astralien3000** [comment]
Ok, je pensais aussi que ça serait la façon la plus simple d'utiliser votre code. Mais ce n'est pas vraiment une fusion... Enfin bon, si il y pas de meilleur solution...

Bon, je vais faire bientôt des tests sur g++ pour ARM, on verra si les résultats ont équivalents à la version pour AVR ou pas. Mais sérieusement ça m'étonnerai qu'il y ai quelque chose dans la version ARM de gcc qui fasse exploser la taille en mémoire.

Par ailleurs un code complet de stratégie sur AtMega128 fait 60Ko en Flash, et tenait sur 4Ko de RAM. Avec représentation interne du terrain, A*, stratégie complexe, asserv, trajectoire, etc...
A titre de comparaison le code C faisait 30Ko en Flash pour entre la moitié et les deux tiers des fonctionnalités.

Sachant que les plus petits STM32 font 4Ko de RAM, ça passe.
Par ailleurs, les plus petits STM32 font 16Ko de Flash.
C'est équivalent à la place sur les gros AVR. Et même une stratégie en C avec Aversive ne tient pas sur cette espace.
Alors bien sûre, on fera pas tourner un code complexe sur les plus petits, mais tu peux voire en regardant mes résultats qu'on peut faire tourner un code d'asserv avec une stratégie simple sur 16Ko je pense.

Par contre, pour les STM8, on passe à 1Ko de RAM et  2Ko de Flash. Ca passe moins, mais faut pas se leurrer, un compilateur C n'est pas un programme magique qui fera tenir une asserv sur 2Ko de Flash.

Bien sûre c'est dans le cas où arm-none-eabi-g++ donne les mêmes résultats que avr-g++.

Donc voila, je comprends et respecte ton choix de ne pas vouloir utiliser le C++, je ne forcerais personne à l'utiliser bien sûre (surtout que la principale raison pour ne pas utiliser le C++ c'est de ne pas aimer l'utiliser tout simplement). Mais par contre j'aime vraiment pas l'argument disant que les codes C++ sont incapables de tenir sur des petits STM32.

**Comment by Kev-J** [comment]
Je serais très intéressé pour avoir tes résultats. Juste pour voir si ils
se rejoignent avec les notres.

Si ma mémoire est bonne : Ce que j'avais fait c'était déclarer une classe
mère et une classe fille de cette dernière. J'ai déclaré une variable de
type classe mère et j'ai instancié une classe fille dessus de façon à testé
le polymorphisme.

Sert toi des outils de dump de symbole pour voir un peu la place qu'occupe
ton programme par rapport à la lib du C++.

Ce n'est pas que j'aime pas le C++, sinon je n'aurais pas testé de
l'intégrer dans ausbee. C'est juste que je trouvais ça trop restrictif
d'avoir de priver de libausbee une gamme de MCU. Aussi, l'architecture AVR
et ARM est très différente. Les chaines de compil aussi. Du coup les
tailles de code ne sont pas comparable.

**Comment by astralien3000** [comment]
# Voila enfin les résultats !

Déjà, voici le code source utilisé : 
https://github.com/astralien3000/code_size
Il y a aussi toutes les données de taille mémoire recueillies au cours des tests, je n'en ai utilisé qu'une partie.

J'ai pas vraiment envie d'expliquer ce que mon code fait en détail.
En gros, je compile de 1 à 9 fonctions qui appliquent une formule à deux nombres passés en paramètres. Lire le code pour plus de détails...

En C, les pointeurs de fonctions sont utilisés pour "feindre" le polymorphisme.
J'ai compilée le même code en C et en C++.
Encore pour le C++, j'ai testé plusieurs méthodes utilisant soit le polymorphisme, soit les templates, soit les deux.

J'ai fais des graphs donnant la taille du code en octets en fonction du nombre de fonctions utilisées (de 1 à 9 donc), selon les méthodes employées. Les tailles de code sont la taille de la section .text en sortie du compilateur arm-none-eabi-g**.

## Résultat
### Général
![graph_all](http://i60.tinypic.com/4lk9jc.jpg)

c void : Main vide en c
cpp void : Main vide en c++
c : Test "témoin" en c
cpp : Test "témoin", compilé avec g++
cpp poly : Code reproduisant le comportement du test témoin avec des classes contenant une méthode virtuelle.
cpp poly2 : Par rapport à cpp poly : ajout de méthodes simples (non virtuelles) à la classe de base (la pente de la courbe doit être la même, avec un offset)
cpp poly3 : Par rapport à cpp poly2 : ajout de plusieurs méthodes virtuelles dans les classes. (la pente doit être plus grande).
cpp templ : Code reproduisant le comptortement du test témoin avec des classes et une fonction template.
cpp mix : Erreur de la nature qui ne devrait pas exister.

Bon déjà, avec ce graphe, on peut virer certains tests qui sont visiblement pas intéressants et se concentrer sur le coeur du sujet : 
![interet](http://i57.tinypic.com/30j4r2u.jpg)

On voit que le polymorphisme augmente pas mal la taille mémoire utilisée. Et cela est proportionnel au nombre de methodes virtuelles. Il faut donc éviter de l'utiliser au maximum, et si il n'y a pas le choix, faire en sorte que seulement une méthode par classe soit virtuelle.
Dans ce cas, on peut peut être parler d'explosion, vu que l'augmentation moyenne de la taille en mémoire sur ARM est de +60% par rapport au C.

### Intéressons nous à la différence C/C++ : 
![cpp](http://i57.tinypic.com/2lcycme.jpg)

Ça m'a étonné, il y a une léger offset pour le C++ alors que c'est le même code.
À notter que seul la version ARM donne cette différence ! Pour AVR et x86, la taille est strictement la même. J'ai scruté le code assembleur généré sans trouver la moinde différence, hors mis le nom des symboles qui change entre le C et le C++ (dû au mangling).

### Et maintenant, intéressons nous à la partie que je préfère !
![templates](http://i62.tinypic.com/2aexgut.jpg)

L'implémentation avec templates est plutôt bonne en terme de consomation mémoire.
Il y a en moyenne 11% de consommation en plus.
En gros, on garde une certaine partie des avantages du polymorphisme, sans entrainer de surconsommation excessive.

A part certains points étranges, le résultat général ne me surprend pas beaucoup. Le polymorphisme est à limiter pour la plupart des domaines, mais garde une utilité dans de nombreux cas (plus pour le code utilisateur qu'une bibliothèque). Les templates apportent des fonctionnalités non négligeables qui en plus ne coûtent pas beaucoup.

## Bonus

En bonus, j'ai comparé le surcout des templates et du polymorphisme en fonction des compilateurs.
J'ai affiché la taille prise en mémoire pour chaque implémentation.

### Avec une fonction
![1](http://i62.tinypic.com/2vbpyki.jpg)

### Avec 9 fonctions
![9](http://i62.tinypic.com/jjvazq.jpg)

### Resultat

On voit bien que les différentes implémentations ont des comportement différents selon les compilateurs, ce qui est surprenant !
Par exemple, entre GCC pour x86 et pour ARM, on passe de +31% à +58% par rapport au C pour le polymorphisme.
On remarque aussi que les templates semblent moins intéressants sur AVR que sur ARM (+34% pour AVR contre +11% sur ARM, par rapport au C).

## Conclusion

J'espère que vous avez eut le courage de lire ce mini rapport.
J'ai essayé de pas trop rentrer dans les détails, parceque si non, il m'aurait fallu un mois pour rédiger le rapport !

**Comment by Kev-J** [comment]
Salut Loic!

Merci à toi pour ces infos. Ca confirme plus ou moins ce qu'on avait
observer : Le C++ sur ARM, ça ne s'adresse pas au petit!

J'aimerais juste avoir une précision sur ton code source. Ta classe "Test"
est allouée de cette manière : #define PARAM(n) Test<n>()
Peut être que j'ai omis quelque chose en lisant ton code, mais dans ce cas,
on ne parle donc pas vraiment de polymorphisme d'un objet. Le cas précis ou
on avait observé une explosion de la taille du code était le suivant (par
exemple):
BaseTest *test = new Test();

Je ne sais pas si tu as moyen de tester ce cas de figure facilement, mais
je pense que ça pourrait nous donner pas mal d'informations.

Ensuite, nous avons un compilateur C++ pour arm dans AUSBEE, il est
simplement pas utilisé. Il peut être envisageable de choisir le langage de
base d'un projet afin de rediriger vers ce compilo. Ensuite, il est vrai
que nous avons déjà notre libausbee écrite en C pour les fonctions
robotiques. Mais, si il est facilement faisable de faire un package linkant
sur la bibliothèque d'aversive, alors pourquoi ne pas l'intégrer de la même
manière que libausbee?

Par contre, je n'ai jamais trop utilisé d'AVR et je ne me rend pas bien
compte du travail à faire pour l'intégrer dans ausbee.

Kev,

**Comment by espitall** [comment]
Sympa les graphes. Malheuresement je suis vraiment une bille en C++ alors j'aurais du mal à interprêter.

Juste une petite remarque sur ton dernier paragraphe Kev-J, je suis en train de faire l'intégration d'AVR dans ausbee. Ca s'annonce plutot bien et je vais du coup ajouter la plateforme "Arduino UNO" par la même occasion en plateforme "officielle".

**Comment by astralien3000** [comment]
Alors le problème est que j'ai complètement supprimé la stdlibc++, donc pas d'opérateur new implémenté.
Tu a du voir que ça explosait justement parceque ça a dû ajouter une partie de la stdlibc++ dans le binaire final. Et là, ça fait mal ! Surtout quand tu a qu'une seule classe implémentée, l'augmentation a dû être très grande en effet. C'est pour ça qu'on a notre propre système de streams, de conteneurs, etc...
Si non j'ai fais ton code en implémentant ma propre version de l'operateur new (à l'arrache), et il n'y a pas de différence, si ce n'est les 40 octets en plus de ma fonction new.

Si non pour l'intégrer de cette façon, ça me va. Mais j'aurai du mal à le faire moi même et tout seul, n'ayant pas d'expérience avec Kconfig. En gros il suffit de faire un make stm32f4 à la racine du projet pour obtenir une lib en ".a" qu'il faut linker avec le projet (avec l'option -l, comme d'hab). La lib se trouve dans le dossier build.
Pour les headers, il faut inclure le dossier /include/stm32.
Après il faut quelques petits option genre le -std=c++1, mais c'est tout.

**Comment by espitall** [comment]
Pour info, la taille qu'affiche ausbee à la fin d'une compilation est actuellement fausse (cf #7). @Kev-J , je ne sais pas si tu as basé tes tests dessus mais pour l'instant, tout le code des fonctions est compté comme de la RAM. Ca peut expliquer peut etre ton explosion de RAM.

**Comment by Kev-J** [comment]
Lors de mes tests, je me souviens que je parlais bien de la taille
programme. A l'époque j'utilisais sûrement la ligne de commande sur le .elf.
