### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by espitall** [Kev-J/ausbee#5]
La licence du projet ausbee est déclaré uniquement dans le README, et ne fait pas référence à une licence reconnue.

Il serait bon de rallier AUSBEE a une licence classique tant que le nombre de contributeur externe est réduit. Un changement de licence après coup est toujours très délicat.

**Comment by Kev-J** [comment]
Salut Damien,

Le problème est que certains fichiers sont copyrighté par St sans licence
connue (CMSIS aussi je crois) . On ne peu donc pas passer tout le projet en
GPL. Du coup on savais pas trop comment faire et on avait mis ça de côté.
As tu une idée ?

Kev

**Comment by espitall** [comment]
Tu peux passer tout le projet en GPL et mettre dans le readme que quelques fichiers viennent d'ailleurs et ont leur propre licence (qu'il faudrait mettre en début de fichier). Si ST n'a rien mis, un simple copyright st, suffira.

Une autre solution serait de profiter du système de download des modules de ausbee pour ne pas les inclures, mais ça alourdi.

Enfin on peut mettre la licence dans le header de chaque fichier mais bon, j'aime pas trop ça. Cela dit j'ai déjà vu que tu met author et version dans les headers, alors pourquoi pas la licence !

De manière générale c'est pas terrible un projet sans licence car par défaut c'est tout sauf open/libre.

**Comment by espitall** [comment]
On est pas loin de pouvoir clore ce sujet. Je pense qu'il ne manque que la mise à jour du README

**Comment by Kev-J** [comment]
Oups ... merci Damien!

2015-06-14 12:03 GMT+02:00 espitall <notifications@github.com>:
